# Generated by Django 4.2.30 on 2026-06-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('archivo_pdf', models.FileField(upload_to='documentos_pdf/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('is_archivado', models.BooleanField(default=False, help_text='Si está marcado, el documento se oculta de la lista general y pasa al archivo de recuperación.', verbose_name='¿Está Archivado?')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cargados', to='formularios.formulariotemplate', verbose_name='Formulario / Plantilla')),
            ],
            options={
                'verbose_name': 'Documento PDF',
                'verbose_name_plural': 'Documentos PDF',
            },
        ),
    ]
