# Generated by Django 4.2.30 on 2026-06-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jerarquia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nodo_jerarquia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area_real', to='jerarquia.nodojerarquia', verbose_name='Nodo de Jerarquía')),
            ],
            options={
                'verbose_name': 'Área de la Empresa',
                'verbose_name_plural': 'Áreas de la Empresa',
            },
        ),
    ]
