# Generated by Django 4.2.30 on 2026-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Formulario')),
                ('tipo_documento', models.CharField(choices=[('MEMO', 'Memorándum Interno'), ('RESOLUCION', 'Resolución Gubernamental / Institucional'), ('MANUAL', 'Manual de Procedimientos / Operativo'), ('CIRCULAR', 'Circular General')], max_length=30, verbose_name='Tipo de Documento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area_propietaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_propios', to='areas.areaempresa', verbose_name='Área Propietaria')),
                ('areas_destinatarias', models.ManyToManyField(blank=True, related_name='formularios_recibidos', to='areas.areaempresa', verbose_name='Áreas Destinatarias (Comunicación Oblicua)')),
            ],
            options={
                'verbose_name': 'Plantilla de Formulario',
                'verbose_name_plural': 'Plantillas de Formularios',
            },
        ),
    ]
